name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get deps
      run: go mod download

    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
       cd example
       go build -v ./...

    - name: Sample run
      run: |
       cd example
       ./example
