name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install linter
      run: |
         curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1
         golangci-lint --version

    - name: Get go deps
      run: go mod download

    - name: Run linter
      run: golangci-lint run

    - name: Tests
      run: |
        go test -v ./...
        go test -race ./...

    - name: Unit tests coverage
      run: |
        make cover

    - name: Build
      run: |
       cd example
       go build -v ./...

    - name: Sample run
      run: |
       cd example
       ./example
